config/routes.rb
Rails.application.routes.draw do
  get 'session/index', as: 'session'
  post "session/index"            => "session#create"

  get 'welcome/index'

  root 'welcome#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  mount Blazer::Engine, at: "blazer"

end

app/models/ahoy/event.rb
module Ahoy
  class Event < ActiveRecord::Base
    include Ahoy::Properties

    self.table_name = "ahoy_events"

    belongs_to :visit
    belongs_to :user, optional: true

    serialize :properties, JSON
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/session.rb
class Session < ApplicationRecord
end

app/models/visit.rb
class Visit < ActiveRecord::Base
  has_many :ahoy_events, class_name: "Ahoy::Event"
  belongs_to :user, optional: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/session_controller.rb
class SessionController < ApplicationController
  def index
  end

  def create
    @session = Session.new(session_params)
    @session.save
    # redirect_to @article
  end

  private

    def session_params
      params.require(:session).permit(:comment)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>GuidedDaydreaming</title>
    <%= csrf_meta_tags %>
    <meta name="viewport" content="width=device-width,initial-scale=1.0">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bulma/0.5.1/css/bulma.css"/>
    <%= stylesheet_link_tag    'application', media: 'all' %>
    <%= javascript_include_tag 'application' %>
    <!-- Hotjar Tracking Code for http://www.guideddaydreaming.com -->
    <script>
        (function(h,o,t,j,a,r){
            h.hj=h.hj||function(){(h.hj.q=h.hj.q||[]).push(arguments)};
            h._hjSettings={hjid:614032,hjsv:5};
            a=o.getElementsByTagName('head')[0];
            r=o.createElement('script');r.async=1;
            r.src=t+h._hjSettings.hjid+j+h._hjSettings.hjsv;
            a.appendChild(r);
        })(window,document,'//static.hotjar.com/c/hotjar-','.js?sv=');
    </script>

      <!-- Open Graph Data -->
      <meta property="og:title" content="Guided Daydreaming"/>
      <meta property="og:type" content="Website" />
      <meta property="og:url" content="https://guideddaydreaming.com" />
      <meta property="og:description" content="Daydream with meaning" />
      <meta property="og:site_name" content="Guided Daydreaming" />
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/session/index.html.erb
<head>
  <%= stylesheet_link_tag params[:controller] %>
</head>


<body id="session">
    <div >
        <div class="circle" id = "bls"></div>
    </div>
    <div id="startingMemory" class="has-text-centered">
      <div>
        <span>Please think of a starting memory or thought.</span>
      </div>
      <div>
        <button id="memoryContinue" class="button is-primary">Continue</button>
      </div>
    </div>
    <div class="has-text-centered">
      <p id="breath">Take a deep breath...</p>
      <p id="wanderText">Please allow your mind to wander and your eyes to follow the moving ball.</p>
    </div>
    <div id="finished" class="field has-text-centered">

      <%= form_for :session do |f| %>
        <div class="field has-text-centered">
          <%= f.label :comment, :class => 'label' %>
          <div class="section">
            <%= f.text_area :comment, :id=>"commentbox", :class => "textarea", :placeholder => "Please leave us feedback!" %>
          </div>
        </div>

        <div>
          <%= f.submit "Submit", :id= => "submitButton", :onclick => "showPostSubmitText()", :class => 'button is-primary is-medium'  %>
          <%= link_to 'Restart', session_path(), class:"button info is-medium" %>
        </div>
      <% end %>
    </div>
    <div id="postSubmitText" class="container has-text-centered">
        <span>Thank you for the feedback!</span>
    </div<>


    <%= javascript_include_tag params[:controller] %>
<body>

app/views/welcome/index.html.erb
<head>
  <%= stylesheet_link_tag params[:controller] %>
</head>

<body>
  <div class="columns is-centered">

    <div id = "logo" class="column is-9-mobile is-offset-1-mobile is-6-desktop">
    <%= image_tag("dark_logo_transparent.svg") %>
  </div>

  </div>
      <section class="section">
      <div class = "container">
          <span>Dreaming at night occurs during the <a href=https://en.wikipedia.org/wiki/Rapid_eye_movement_sleep>REM</a> stage of sleep.</span><br/>
          <span>During this stage, our eyes move rapidly back and forth. This is thought to help us make associations and form memories.</span></br></br>
          <span>In Guided Daydreaming, we mimic this action to help enhance daydreaming.</span>
      </div>
      </section>

        <div class="container">
          <h4 class="title">Instructions:</h4>
          <section class="content">
            <ol class ="subtitle">
              <li class="instructionList">Think of a specific memory.</li>
              <li class="instructionList">When you start, a ball will move back and forth across your screen.</li>
              <li class="instructionList">Follow the ball with your eyes and let your mind freely wander.</li>
              <li class="instructionList">When the ball stops, let the question that appears guide you down a different path.</li>
            </ol>
            <span><strong>Remember:</strong> daydreaming is fun. Don't worry if you don't have a response to a question.</span><br/><br>
            <div class="has-text-centered">
              <span>We look forward to your feedback!</span>
            </div>
          </section>


      <div class = has-text-centered>
          <%= link_to 'Begin', session_path(), id:"beginButton", class:"button is-primary" %>
      </div>
    </div>
  </section>
  <br/>
  <footer class="footer intro">
    <div class="container">
      <div class="content has-text-right">
        <p>
          <a id="sourceCode" href="https://github.com/marwaybs/guidedDaydreaming">Source Code</a>
        </p>
      </div>
    </div>
  </footer>
  <%= javascript_include_tag params[:controller] %>
</body>